snd-soc-sst-dsp-objs := sst_dsp.o sst_dsp_fw.o sst_dsp_hsw.o
snd-soc-sst-hsw-pcm-objs := sst_hsw_ipc.o sst_hsw_pcm.o
snd-soc-sst-hsw-ult-mach-objs := haswell-ult.o

obj-$(CONFIG_SND_SOC_INTEL_SST) += snd-soc-sst-dsp.o
obj-$(CONFIG_SND_SOC_INTEL_HSWULT) += snd-soc-sst-hsw-pcm.o
obj-$(CONFIG_SND_SOC_INTEL_HSWULT_MACH) += snd-soc-sst-hsw-ult-mach.o
